// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Os = require("os");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var encoding = "utf8";

function removeEmpty(lines) {
  return Belt_Array.keep(lines, (function (line) {
                return line.length !== 0;
              }));
}

function readTodos(filename) {
  if (Fs.existsSync(filename)) {
    return removeEmpty(Fs.readFileSync(filename, {
                      encoding: encoding,
                      flag: "r"
                    }).split(Os.EOL));
  } else {
    Fs.writeFileSync(filename, "", {
          encoding: encoding,
          flag: "w"
        });
    return [];
  }
}

function writeTodos(filename, todos) {
  var todoText = todos.join(Os.EOL);
  Fs.writeFileSync(filename, todoText, {
        encoding: encoding,
        flag: "w"
      });
  
}

function updateFile(filename, updater) {
  var contents = readTodos(filename);
  return writeTodos(filename, Curry._1(updater, contents));
}

function appendTodos(filename, todo) {
  Fs.appendFileSync(filename, todo + Os.EOL, {
        encoding: encoding,
        flag: "a"
      });
  
}

exports.encoding = encoding;
exports.removeEmpty = removeEmpty;
exports.readTodos = readTodos;
exports.writeTodos = writeTodos;
exports.updateFile = updateFile;
exports.appendTodos = appendTodos;
/* fs Not a pure module */
