// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Commands = require("./commands.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var pendingTodosFile = "todo.txt";

var completedTodosFile = "done.txt";

var help = "Usage :-\n$ ./todo add \"todo item\"  # Add a new todo\n$ ./todo ls               # Show remaining todos\n$ ./todo del NUMBER       # Delete a todo\n$ ./todo done NUMBER      # Complete a todo\n$ ./todo help             # Show usage\n$ ./todo report           # Statistics".trim();

var argv = process.argv;

var argc = argv.length;

if (argc <= 2) {
  console.log(help);
} else {
  var command = Caml_array.get(argv, 2);
  var args = argc > 3 ? Belt_Array.sliceToEnd(argv, 3) : [];
  switch (command) {
    case "add" :
        Commands.cmdAddTodo(args, pendingTodosFile);
        break;
    case "del" :
        Commands.cmdDelTodo(args, pendingTodosFile);
        break;
    case "done" :
        Commands.cmdDoneTodo(args, pendingTodosFile, completedTodosFile);
        break;
    case "ls" :
        Commands.cmdLs(pendingTodosFile);
        break;
    case "report" :
        Commands.cmdReport(pendingTodosFile, completedTodosFile);
        break;
    default:
      Commands.cmdHelp(help);
  }
}

exports.pendingTodosFile = pendingTodosFile;
exports.completedTodosFile = completedTodosFile;
exports.help = help;
exports.argv = argv;
exports.argc = argc;
/* help Not a pure module */
