// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function deleteItem(arr, delIndex) {
  return Belt_Array.reduceWithIndex(arr, [], (function (acc, element, index) {
                if (index !== delIndex) {
                  return [element].concat(acc);
                } else {
                  return acc;
                }
              }));
}

var getToday = (function() {
  let date = new Date();
  return new Date(date.getTime())
    .toISOString()
    .split("T")[0];
});

exports.deleteItem = deleteItem;
exports.getToday = getToday;
/* No side effect */
